# -*- coding: utf-8 -*-
"""CV lab 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sAy3if7q11GnEoiZb_s7nFMeYypjXL2
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

r_min=100
r_max=200
img=cv2.imread("/content/space-odyssey.jpg",0)
slicing_w_o_background=np.zeros(img.shape)
slicing_w_background=img.copy()
for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    pixel_value=img[i][j]
    if r_min<=pixel_value<=r_max:
      slicing_w_o_background[i][j]=255
      slicing_w_background[i][j]=255

def show_images(images, titles=None):
    n_images = len(images)
    plt.figure(figsize=(15, 5))
    for i, img in enumerate(images):
        plt.subplot(1, n_images, i + 1)
        plt.imshow(img, cmap='gray')
        if titles:
            plt.title(titles[i])
        plt.axis('off')
    plt.tight_layout()
    plt.show()

show_images([img, slicing_w_o_background, slicing_w_background], titles=['Original Image', 'Slicing Without Background', 'Slicing With Background'])